### ISSUE TITLE
Hash the password before saving

### ISSUE THREAD

**Issue by Keerat666** [Keerat666/ExpressJS-Starter-Template#5]
- Inside the User Controller, before signup hash the password and then store it to the database 
- Make the required changes for the login logic as well

**Comment by probro27** [comment]
@Keerat666 I think I can work on this. Please assign it to me :)

**Comment by probro27** [comment]
Hi @Keerat666 Thanks for assigning me the issue. Please review my PR whenever possible :)

**Comment by arol** [comment]
I see the PR has been merged, can we close the issue?
